### ISSUE TITLE
NASA Exoplanet Archive API update

### ISSUE THREAD

**Issue by rpoleski** [mtpenny/wfirst-ml-figures#4]
I wanted to re-plot the main plot from Matt's paper using current catalog of exoplanets for a presentation. The script failed at downloading CSV files. I've asked helpdesk about that and they send me how the API change 3 years ago:

OLD: `wget 'https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=cumulative&select=*&format=csv&'`
NEW: `wget 'https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+cumulative&format=csv'`

OLD: `wget 'https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets'`
NEW: `wget 'https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+ps+where+default_flag=1&format=csv'`

plus they noted the format obtained may be slightly different. I gave the presentation before they answered, so I'm not going to implement it now and only post it here so that somebody can implement that change.

**Comment by mtpenny** [comment]
Thanks Radek! I've updated the code (and fixed some exception handling bugs while I was at it).
